update instructions for fixing compaction based on version numbers

diff --git a/check-riak b/check-riak
--- a/check-riak
+++ b/check-riak
@@ -118,6 +118,10 @@ show_compaction() {
 	header 'Checking Compaction Errors'
 	cd "$db_dir" || { echo "unknown: failed to cd to '$db_dir'"; return 3; }
 	local a=$(find . -name 'LOG' -exec grep -l 'Compaction error' {} \;)
+	local clean_riak_version=${riak_version%%[^0-9.]*} # ex. 1.3.1v1 => 1.3.1
+
+	local tmp=${clean_riak_version//[^0-9]/}
+	local num_riak_version=$(( 10#$tmp )) # ex. 1.3.1 => 131
 
 	if [[ -z "$a" ]]; then
 		echo 'ok: no compaction errors found'
@@ -128,18 +132,54 @@ show_compaction() {
 			echo "critical: $(wc -l <<< "$a") compaction error(s) found"
 		else
 			# interactive
-			cat <<-EOF
-			-------- Compaction errors found! --------
-			The following steps will resolve them
-			$_bold** stop the process before running!! **$_reset
+			echo '-------- Compaction errors found! --------'
+			if (( $num_riak_version < 120 )); then
+				cat <<-EOF
+				[debug] You are running a riak version < 1.2.0 ($riak_version), using erlang shell
 
-			# Run the following command(s) one-by-one
-			# (safe to run multiple commands at the same time to saturate disks)
-			EOF
-			while read line; do
-				tmp=${line/.\//}; dbname=${tmp%%\/*}
-				printf '%s "%s" "%s/%s"\n' "$escript" "$lvlfix" "$db_dir" "$dbname"
-			done <<< "$a"
+				# Start the erl shell
+				$erl
+
+				# Copy this in
+				[application:set_env(eleveldb, Var, Val) || {Var, Val} <-
+				[{max_open_files, 2000},
+				{block_size, 1048576},
+				{cache_size, 20*1024*1024*1024},
+				{sync, false},
+				{data_root, "$db_dir"}]].
+
+				# Drop the following command(s) in one-by-one
+				EOF
+				while read line; do
+					tmp=${line/.\//}; dbname=${tmp%%\/*};
+					printf 'eleveldb:repair("/var/db/riak/leveldb/%s", []).\n' "$dbname"
+				done <<< "$a"
+			elif grep -q '^1.2' <<< "$riak_version"; then
+				# riak 1.2 can use lvlfix
+				cat <<-EOF
+				[debug] You are running a 1.2.X version of riak ($riak_version), using lvlfix.erl
+
+				The following steps will resolve them
+				$_bold** stop the process before running!! **$_reset
+
+				# Run the following command(s) one-by-one
+				# (safe to run multiple commands at the same time to saturate disks)
+				EOF
+				while read line; do
+					tmp=${line/.\//}; dbname=${tmp%%\/*}
+					printf '%s "%s" "%s/%s"\n' "$escript" "$lvlfix" "$db_dir" "$dbname"
+				done <<< "$a"
+			else
+				# 1.3 or up, no known fix
+				cat <<-EOF
+				[debug] You are running a riak version >= 1.3.0 ($riak_version), no known solution
+
+				Compaction errors now have a way of fixing themselves automatically.
+
+				If the errors do not resolve automatically, then this would be a time to use
+				your Basho support contract or check out the IRC channels
+				EOF
+			fi
 		fi
 		ret=2
 	fi
@@ -318,7 +358,7 @@ done
 shift $((OPTIND - 1))
 
 riak_pid=$(pgrep -f '/riak/.*/beam.smp')
-riak_version=$(riak version 2>&1 | awk '/^riak/ { gsub(/[^0-9.]/, "", $2); print $2; }')
+riak_version=$(riak version 2>&1 | awk '/^riak/ { match($0, /([0-9][^ ]+)/); print substr($0, RSTART, RLENGTH); }')
 
 case "$1" in
 	compaction) show_compaction;;
